CREATE TABLE VECTOR (PKEY INTEGER PRIMARY KEY AUTOINCREMENT, VECTOR_NAME VARCHAR(25), VECTORSEQUENCERAW VARCHAR(4000), VECTORCOMMENTS VARCHAR(4000), SGCRESTRICTENZ1_PKEY INT, SGCRESTRICTENZ2_PKEY INT, PROTEASE_PRODUCT VARCHAR(4000), PROTEASE_NAME VARCHAR(4000), PROTEASE_CUTSEQUENCE VARCHAR(4000), REQUIRED_EXTENSION_FORWARD VARCHAR(4000), REQUIRED_EXTENSION_REVERSE VARCHAR(4000), ANTIBIOTIC VARCHAR(4000));
CREATE TABLE TARGET (PKEY INTEGER PRIMARY KEY, TARGET_ID TEXT UNIQUE, GENBANK_ID TEXT, DNASEQ TEXT, PROTSEQ TEXT);
CREATE TABLE ENTRY_CLONE (PKEY INTEGER PRIMARY KEY AUTOINCREMENT, ENTRY_CLONE_ID VARCHAR(20), SGCTARGET_PKEY INT, STATUS VARCHAR(30), SEQSOURCE VARCHAR(4000), DNARAWSEQUENCE TEXT);
CREATE TABLE PRIMER (PKEY INTEGER PRIMARY KEY AUTOINCREMENT, PRIMERNAME VARCHAR(250),PRIMERRAWSEQUENCE VARCHAR(4000));
CREATE TABLE PRIMERREV (PKEY INTEGER PRIMARY KEY AUTOINCREMENT, PRIMERNAME VARCHAR(250),PRIMERRAWSEQUENCE VARCHAR(4000));
CREATE TABLE PLATE (PKEY INTEGER PRIMARY KEY AUTOINCREMENT, PLATENAME VARCHAR(400));
CREATE TABLE ALLELE (PKEY INTEGER PRIMARY KEY AUTOINCREMENT, ALLELE_ID VARCHAR(20), ALLELEPROTSEQ TEXT, ALLELESEQLENGTH INT, ALLELESEQUENCERAW TEXT, SGCPRIMER5_PKEY INT, SGCPRIMER3_PKEY INT, SGCPLATE_PKEY INT, SGCENTRYCLONE_PKEY INT);;
CREATE TABLE CONSTRUCTPLATE (PKEY INTEGER PRIMARY KEY AUTOINCREMENT, PLATENAME VARCHAR(400));
CREATE TABLE CONSTRUCT (PKEY INTEGER PRIMARY KEY AUTOINCREMENT, CONSTRUCT_ID VARCHAR(30), WELLID VARCHAR(3), STATUS VARCHAR(30), SGCVECTOR_PKEY INT, SGCRESTRICTENZ1_PKEY INT, SGCRESTRICTENZ2_PKEY INT, CONSTRUCTPROTSEQ TEXT, CONSTRUCTPROTSEQNOTAG TEXT, CONSTRUCTDNASEQ TEXT, SGCALLELE_PKEY INT, SGCCONSTRUCTPLATE_PKEY INT, CONSTRUCTSTART VARCHAR(400), CONSTRUCTSTOP VARCHAR(400), EXPECTEDMASS FLOAT, EXPECTEDMASSNOTAG FLOAT, EXPETCEDMASSNOTAG FLOAT);
CREATE TABLE TIDDLY_WIKI ("PKEY" INTEGER PRIMARY KEY NOT NULL , "PAGEID" VARCHAR NOT NULL UNIQUE , "CONTENT" TEXT NOT NULL );
CREATE TABLE RESTRICTION_ENZYME ("PKEY" INTEGER PRIMARY KEY NOT NULL , "RESTRICTION_ENZYME_NAME" VARCHAR NOT NULL UNIQUE , "RESTRICTION_ENZYME_SEQUENCERAW" TEXT NOT NULL );
CREATE TABLE SCRIPTS ("PKEY" INTEGER PRIMARY KEY NOT NULL , "NAME" VARCHAR NOT NULL UNIQUE , "VALUE" TEXT NOT NULL );



